namespace: boozeandbites-dev
resources:
  - ../../base/BoozeAndBites-Vue/deployment.yaml
  - ../../base/BoozeAndBites-Vue/service.yaml
  - ../../base/BoozeAndBites-Vue/ingress.yaml
  - ../../base/BoozeAndBites-Vue/grafana-sidecar.yaml
  - namespace.yaml
