name: Deploy to MicroK8s (Dev)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_LOCAL }}" | base64 -d > ~/.kube/config

      - name: Check connection to cluster
        run: kubectl version --client=true

      - name: Show rendered manifests
        run: kubectl kustomize overlays/boozeandbites-dev

      - name: Deploy via kubectl (skip validation)
        run: kubectl apply -k overlays/boozeandbites-dev --validate=false

