name: Deploy to MicroK8s (Dev)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_LOCAL }}" | base64 -d > ~/.kube/config

      - name: Check cluster connection
        run: kubectl version --short

      - name: Deploy with kubectl and kustomize
        run: kubectl apply -k overlays/boozeandbites-dev
